mysite/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    # path(''),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results', views.results, name='results'),
    path('<int:question_id>/votes', views.votes, name='votes'),
]

polls/models.py
import datetime
from django.utils import timezone
from django.db import models

# Create your models here.
class Question(models.Model):
    question_txt = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Date_Published')

    def __str__(self):
        return self.question_txt
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_txt = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)    

    def __str__(self):
        return self.choice_txt

polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from polls.models import Question, Choice

# Create your views here.
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:10]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


def votes(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_msg': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))  

polls/templates/polls/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'polls/style.css' %}" />
    <title>Document</title>
  </head>
  <body>
    <form action="{% url 'polls:votes' question.id %}" method="post">
      {% csrf_token %}
      <legend><h1>{{ question.question_txt }}</h1></legend>
      {% if error_msg %}
      <p><strong>{{ error_msg }}</strong></p>
      {% endif %} {% for choice in question.choice_set.all %}
      <input
        type="radio"
        name="choice"
        id="choice{{ forloop.counter }}"
        value="{{ choice.id }}"
      />
      <label for="choice{{ forloop.counter }}">{{ choice.choice_txt }}</label
      ><br />
      {% endfor %}
      <input type="submit" value="Vote" />
    </form>
  </body>
</html>

polls/templates/polls/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'polls/style.css' %}"
    />
    <title>Document</title>
  </head>
  <body>
    <h1>Polls app</h1>
    <h3>choose a question:</h3>
    {% if latest_question_list %}
    <ol>
      {% for question in latest_question_list %}
      <li>
        <a href="{% url 'polls:detail' question.id %}"
          >{{ question.question_txt }}</a
        >
      </li>
      {% endfor %}
    </ol>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
  </body>
</html>

polls/templates/polls/results.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'polls/style.css'%}" />
    <title>results page</title>
  </head>
  <body>
    <h1>{{ question.question_txt }}</h1>
    <ol>
      {% for choice in question.choice_set.all %}
      <li>{{ choice.choice_text }} -- {{ choice.votes }} votes</li>
      {% endfor %}
    </ol>
    <a href="{% url 'polls:detail' question.id %}">Vote Again</a>
  </body>
</html>